### ISSUE TITLE
Compilation Bugs

### ISSUE THREAD

**Issue by thomas-lamiaux** [amblafont/thomas#2]
J'ai actuellement les bugs suivant à la compilation (indépendant du compileur) : 

- [x] `Package pgfkeys: I do not know the key '/tikz/curve', to which you passed 'ratio=-0.5', and I am going to ignore it. Perhaps you misspelled it.`
- [x] `I found no \citation commands`

**Comment by thomas-lamiaux** [comment]
Le problème est réglé de mon coté. De ce que je vois, cela vient d'un fix dans yade. 
Toutefois, pourrais tu me confirmer que tu vois ces messages ?

**Comment by thomas-lamiaux** [comment]
Test @amblafont

**Comment by amblafont** [comment]
celui ci n'a pas marche, mais je viens de changer qq chose. tu peux ressayer ?

**Comment by thomas-lamiaux** [comment]
@amblafont try
